/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danim
 */
import java.util.ArrayList;
import java.util.List;

import java.io.File;
import java.awt.Desktop;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

public class FrameRecetas extends javax.swing.JFrame {
private int idConsultaActual;
private List<Object[]> filasPendientes = new ArrayList<>(); // {idMedicamento, nombreMostrado, dosis, frecuencia, duracion}

    /**
     * Creates new form FrameRecetas
     */
    public FrameRecetas() {
        initComponents();
        cargarComboMedicamento();
        inicializarTablaMedicamentos();
    }
    public FrameRecetas(int idConsulta) {
    initComponents();
    this.idConsultaActual = idConsulta;
    cargarComboMedicamento();
    // Deja fijo el combo de consulta mostrando solo esta consulta (no dejes cambiarlo)
    javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
    modelo.addElement(new ComboItem(String.valueOf(idConsulta), "Consulta #" + idConsulta));
    jComboBoxConsultaReceta.setModel(modelo);
    jComboBoxConsultaReceta.setEnabled(false);
    inicializarTablaMedicamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxConsultaReceta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextAreaIndicacionesGenerales = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxMedicamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDosis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldFrecuencia = new javax.swing.JTextField();
        jTextFieldDuracion = new javax.swing.JTextField();
        jButtonQuitarMedicamento = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicamentosReceta = new javax.swing.JTable();
        jButtonGuardarReceta = new javax.swing.JButton();
        jButtonImprimirReceta = new javax.swing.JButton();
        jButtonLimpiarReceta = new javax.swing.JButton();
        jButtonRegresarAlMenu = new javax.swing.JButton();
        jLabelStatusReceta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Emitir Receta");

        jLabel2.setText("Consulta Asociada");

        jComboBoxConsultaReceta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Indicaciones Generales");

        jLabel4.setText("Medicamentos de la Receta");

        jLabel5.setText("Medicamento");

        jComboBoxMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Dosis (mg)");

        jTextFieldDosis.setText("500 ");
        jTextFieldDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDosisActionPerformed(evt);
            }
        });

        jLabel7.setText("Frecuencia");

        jLabel8.setText("Duración");

        jTextFieldFrecuencia.setText("8 horas");

        jTextFieldDuracion.setText("1 semana");
        jTextFieldDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDuracionActionPerformed(evt);
            }
        });

        jButtonQuitarMedicamento.setText("Quitar");
        jButtonQuitarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarMedicamentoActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Medicamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTableMedicamentosReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMedicamentosReceta);

        jButtonGuardarReceta.setBackground(new java.awt.Color(153, 204, 255));
        jButtonGuardarReceta.setText("Guardar Receta");
        jButtonGuardarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarRecetaActionPerformed(evt);
            }
        });

        jButtonImprimirReceta.setText("Imprimir");
        jButtonImprimirReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirRecetaActionPerformed(evt);
            }
        });

        jButtonLimpiarReceta.setText("Limpiar");
        jButtonLimpiarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarRecetaActionPerformed(evt);
            }
        });

        jButtonRegresarAlMenu.setText("Regresar");
        jButtonRegresarAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarAlMenuActionPerformed(evt);
            }
        });

        jLabelStatusReceta.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jComboBoxConsultaReceta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                            .addComponent(jTextAreaIndicacionesGenerales)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxMedicamento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDosis, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldFrecuencia, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonQuitarMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonGuardarReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonImprimirReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiarReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegresarAlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelStatusReceta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConsultaReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAreaIndicacionesGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButtonQuitarMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarReceta)
                    .addComponent(jButtonImprimirReceta)
                    .addComponent(jButtonLimpiarReceta)
                    .addComponent(jButtonRegresarAlMenu))
                .addGap(18, 18, 18)
                .addComponent(jLabelStatusReceta)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarMedicamentoActionPerformed
        // TODO add your handling code here:
        int fila = jTableMedicamentosReceta.getSelectedRow();
    if (fila == -1) return;

    filasPendientes.remove(fila);
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTableMedicamentosReceta.getModel();
    modelo.removeRow(fila);
    }//GEN-LAST:event_jButtonQuitarMedicamentoActionPerformed

    private void jTextFieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDuracionActionPerformed

    private void jButtonImprimirRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirRecetaActionPerformed
        // TODO add your handling code here:
       if (filasPendientes.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No hay medicamentos agregados para imprimir la receta.", 
                "Atención", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombreArchivo = "Receta_Consulta_" + idConsultaActual + ".pdf";

        try {
            // Inicializar PdfWriter y PdfDocument de iText 8
            PdfWriter writer = new PdfWriter(nombreArchivo);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document document = new Document(pdfDoc);

            // Título
            Paragraph title = new Paragraph("RECETA MÉDICA")
                    .setFontSize(18)
                    .setBold()
                    .setFontColor(ColorConstants.BLUE)
                    .setTextAlignment(TextAlignment.CENTER);
            document.add(title);
            document.add(new Paragraph("\n"));

            // Datos
            document.add(new Paragraph("Consulta N°: " + idConsultaActual).setBold());
            document.add(new Paragraph("Indicaciones Generales: " + jTextAreaIndicacionesGenerales.getText().trim()));
            document.add(new Paragraph("\n"));

            // Tabla (con ancho relativo al 100%)
            Table table = new Table(UnitValue.createPercentArray(new float[]{4, 2, 2, 2}));
            table.setWidth(UnitValue.createPercentValue(100));

            // Encabezados
            String[] headers = {"Medicamento", "Dosis", "Frecuencia", "Duración"};
            for (String header : headers) {
                Cell cell = new Cell()
                        .add(new Paragraph(header).setBold())
                        .setBackgroundColor(ColorConstants.LIGHT_GRAY)
                        .setTextAlignment(TextAlignment.CENTER);
                table.addHeaderCell(cell);
            }

            // Filas
            for (Object[] fila : filasPendientes) {
                table.addCell(new Cell().add(new Paragraph(fila[1].toString())));
                table.addCell(new Cell().add(new Paragraph(fila[2].toString())));
                table.addCell(new Cell().add(new Paragraph(fila[3].toString())));
                table.addCell(new Cell().add(new Paragraph(fila[4].toString())));
            }

            document.add(table);
            document.close();

            // Abrir el archivo PDF
            File pdfFile = new File(nombreArchivo);
            if (pdfFile.exists() && Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(pdfFile);
            }

            jLabelStatusReceta.setText("PDF generado correctamente: " + nombreArchivo);

        } catch (Exception e) {
            jLabelStatusReceta.setText("Error al generar PDF: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonImprimirRecetaActionPerformed

    private void jTextFieldDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDosisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ComboItem medicamento = (ComboItem) jComboBoxMedicamento.getSelectedItem();

    if (medicamento == null || jTextFieldDosis.getText().trim().isEmpty()
            || jTextFieldFrecuencia.getText().trim().isEmpty()
            || jTextFieldDuracion.getText().trim().isEmpty()) {
        return; // si tienes un jLabel de status, avisa aquí
    }

    filasPendientes.add(new Object[]{
        Integer.parseInt(medicamento.getId()),
        medicamento.toString(),
        jTextFieldDosis.getText().trim(),
        jTextFieldFrecuencia.getText().trim(),
        jTextFieldDuracion.getText().trim()
    });

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTableMedicamentosReceta.getModel();
    modelo.addRow(new Object[]{
        medicamento.toString(),
        jTextFieldDosis.getText().trim(),
        jTextFieldFrecuencia.getText().trim(),
        jTextFieldDuracion.getText().trim()
    });

    jTextFieldDosis.setText("");
    jTextFieldFrecuencia.setText("");
    jTextFieldDuracion.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonGuardarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarRecetaActionPerformed
        // TODO add your handling code here:
        if (idConsultaActual == 0) {
        return; // no debería pasar si siempre abres este frame desde "Ir a Receta"
    }

    try {
        // filasPendientes trae {idMedicamento, nombreMostrado, dosis, frecuencia, duracion}
        // RecetaDAO solo necesita {idMedicamento, dosis, frecuencia, duracion}
        List<Object[]> filasParaGuardar = new ArrayList<>();
        for (Object[] fila : filasPendientes) {
            filasParaGuardar.add(new Object[]{fila[0], fila[2], fila[3], fila[4]});
        }

        RecetaDAO.guardarRecetaCompleta(idConsultaActual,
                jTextAreaIndicacionesGenerales.getText().trim(),
                filasParaGuardar);

        javax.swing.JOptionPane.showMessageDialog(this, "Receta guardada correctamente.");
        jLabelStatusReceta.setText("Receta guardada correctamente.");
    } catch (java.sql.SQLException e) {
        jLabelStatusReceta.setText("Error al guardar la receta: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonGuardarRecetaActionPerformed

    private void jButtonLimpiarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarRecetaActionPerformed
        // TODO add your handling code here:
        filasPendientes.clear();
    inicializarTablaMedicamentos();
    jTextAreaIndicacionesGenerales.setText("");
    jTextFieldDosis.setText("");
    jTextFieldFrecuencia.setText("");
    jTextFieldDuracion.setText("");
    }//GEN-LAST:event_jButtonLimpiarRecetaActionPerformed

    private void jButtonRegresarAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarAlMenuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonRegresarAlMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRecetas().setVisible(true);
            }
        });
    }
    
    
    private void cargarComboMedicamento() {
    try {
        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        for (Object[] fila : MedicamentoDAO.listarTodos()) {
            String id = fila[0].toString();
            String nombre = fila[1] + " (" + fila[2] + " " + fila[3] + ")";
            modelo.addElement(new ComboItem(id, nombre));
        }
        jComboBoxMedicamento.setModel(modelo);
    } catch (java.sql.SQLException e) {
        // si tienes un jLabel de status en este frame, muéstralo ahí
        jLabelStatusReceta.setText("Error al cargar medicamentos: " + e.getMessage());
    }
}

// ===== Preparar la tabla visual de medicamentos de la receta =====
private void inicializarTablaMedicamentos() {
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTableMedicamentosReceta.getModel();
    modelo.setRowCount(0);
    modelo.setColumnIdentifiers(new String[]{"Medicamento", "Dosis", "Frecuencia", "Duración"});
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonGuardarReceta;
    private javax.swing.JButton jButtonImprimirReceta;
    private javax.swing.JButton jButtonLimpiarReceta;
    private javax.swing.JButton jButtonQuitarMedicamento;
    private javax.swing.JButton jButtonRegresarAlMenu;
    private javax.swing.JComboBox<String> jComboBoxConsultaReceta;
    private javax.swing.JComboBox<String> jComboBoxMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelStatusReceta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicamentosReceta;
    private javax.swing.JTextField jTextAreaIndicacionesGenerales;
    private javax.swing.JTextField jTextFieldDosis;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldFrecuencia;
    // End of variables declaration//GEN-END:variables
}
