/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danim
 */

import java.util.List;


public class FrameInternamiento extends javax.swing.JFrame {

    /**
     * Creates new form FrameInternamiento
     */
    
    
    private int idInternamientoSeleccionado = -1;
    
    public FrameInternamiento() {
        initComponents();
        jDateChooserEntrada.setEnabled(false);
    jDateChooserSalida.setEnabled(false);
        cargarComboPacientes();
        cargarComboMedicos();
        cargarTablaInternamientos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxTipoPaciente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxPacienteInt = new javax.swing.JComboBox<>();
        jComboBoxMedicoResponsable = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jDateChooserEntrada = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMotivoEntrada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextAreaObsEntrada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserSalida = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxMotivoSalida = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextAreaObsSalida = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInternamientos = new javax.swing.JTable();
        jButtonRegistrarEntrada = new javax.swing.JButton();
        jButtonRegistrarSalida = new javax.swing.JButton();
        jButtonLimpiarInternamiento = new javax.swing.JButton();
        jButtonRegresaralMenu = new javax.swing.JButton();
        jButtonActualizarInternamiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Internamiento (Entrada)");

        jLabel2.setText("Paciente");

        jLabel3.setText("Médico Responsable");

        jLabel4.setText("Tipo de Paciente");

        jLabel5.setText("Fecha de Entrada");

        jComboBoxPacienteInt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxMedicoResponsable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospitalizado", "Urgencias", "Ambulatorio" }));

        jLabel6.setText("Motivo de entrada");

        jTextFieldMotivoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMotivoEntradaActionPerformed(evt);
            }
        });

        jLabel7.setText("Observaciones");

        jLabel8.setText("Registrar Salida");

        jLabel10.setText("Fecha de salida");

        jLabel11.setText("Motivo de Salida");

        jComboBoxMotivoSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta médica", "Traslado", "Voluntaria", "Defuncion" }));

        jLabel12.setText("Observaciones");

        jLabel13.setText("Internador");

        jTableInternamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableInternamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableInternamientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableInternamientos);

        jButtonRegistrarEntrada.setText("Registrar Entrada");
        jButtonRegistrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarEntradaActionPerformed(evt);
            }
        });

        jButtonRegistrarSalida.setText("Registrar Salida");
        jButtonRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarSalidaActionPerformed(evt);
            }
        });

        jButtonLimpiarInternamiento.setText("Limpiar");
        jButtonLimpiarInternamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarInternamientoActionPerformed(evt);
            }
        });

        jButtonRegresaralMenu.setText("Regresar");
        jButtonRegresaralMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresaralMenuActionPerformed(evt);
            }
        });

        jButtonActualizarInternamiento.setText("Actualizar");
        jButtonActualizarInternamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarInternamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jComboBoxTipoPacienteLayout = new javax.swing.GroupLayout(jComboBoxTipoPaciente);
        jComboBoxTipoPaciente.setLayout(jComboBoxTipoPacienteLayout);
        jComboBoxTipoPacienteLayout.setHorizontalGroup(
            jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jComboBoxTipoPacienteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jComboBoxTipoPacienteLayout.createSequentialGroup()
                        .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jComboBoxTipoPacienteLayout.createSequentialGroup()
                                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMotivoEntrada, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxPacienteInt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(jComboBoxTipoPacienteLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxMotivoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextAreaObsEntrada)
                            .addGroup(jComboBoxTipoPacienteLayout.createSequentialGroup()
                                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxMedicoResponsable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(jDateChooserEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jComboBoxTipoPacienteLayout.createSequentialGroup()
                        .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jComboBoxTipoPacienteLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jComboBoxTipoPacienteLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextAreaObsSalida)))
                        .addGap(109, 109, 109))
                    .addGroup(jComboBoxTipoPacienteLayout.createSequentialGroup()
                        .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jComboBoxTipoPacienteLayout.createSequentialGroup()
                                .addComponent(jButtonRegistrarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRegistrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLimpiarInternamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonActualizarInternamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRegresaralMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(338, Short.MAX_VALUE))))
        );
        jComboBoxTipoPacienteLayout.setVerticalGroup(
            jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jComboBoxTipoPacienteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxPacienteInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMedicoResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMotivoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAreaObsEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMotivoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextAreaObsSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jComboBoxTipoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarEntrada)
                    .addComponent(jButtonRegistrarSalida)
                    .addComponent(jButtonLimpiarInternamiento)
                    .addComponent(jButtonActualizarInternamiento)
                    .addComponent(jButtonRegresaralMenu))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBoxTipoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBoxTipoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMotivoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMotivoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMotivoEntradaActionPerformed

    private void jButtonRegistrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarEntradaActionPerformed
        // TODO add your handling code here:
        ComboItem paciente = (ComboItem) jComboBoxPacienteInt.getSelectedItem();
    ComboItem medico = (ComboItem) jComboBoxMedicoResponsable.getSelectedItem();

    if (paciente == null || medico == null || jTextFieldMotivoEntrada.getText().trim().isEmpty()) {
        jLabel13.setText("Selecciona paciente, médico y escribe el motivo de entrada.");
        return;
    }

    try {
        InternamientoDAO.registrarEntrada(
                paciente.getId(),
                Integer.parseInt(medico.getId()),
                jComboBox3.getSelectedItem().toString(), // tipo de paciente
                jTextFieldMotivoEntrada.getText().trim(),
                jTextAreaObsEntrada.getText().trim()
        );
        jLabel13.setText("Entrada registrada a las "
                + java.time.LocalTime.now().withNano(0) + ".");
        jTextFieldMotivoEntrada.setText("");
        jTextAreaObsEntrada.setText("");
        cargarTablaInternamientos();
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al registrar entrada: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonRegistrarEntradaActionPerformed

    private void jTableInternamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableInternamientosMouseClicked
        // TODO add your handling code here:
        int fila = jTableInternamientos.getSelectedRow();
    if (fila == -1) return;

    idInternamientoSeleccionado = (int) jTableInternamientos.getValueAt(fila, 0);
    String estado = jTableInternamientos.getValueAt(fila, 6).toString();

    if (!"activo".equals(estado)) {
        jLabel13.setText("Este internamiento ya tiene salida registrada.");
    } else {
        jLabel13.setText("Internamiento #" + idInternamientoSeleccionado + " listo para registrar salida.");
    }
    }//GEN-LAST:event_jTableInternamientosMouseClicked

    private void jButtonRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarSalidaActionPerformed
        // TODO add your handling code here:
        if (idInternamientoSeleccionado == -1) {
        jLabel13.setText("Selecciona en la tabla el internamiento al que le vas a dar salida.");
        return;
    }
    if (jComboBoxMotivoSalida.getSelectedItem() == null) {
        jLabel13.setText("Selecciona el motivo de salida.");
        return;
    }

    try {
        InternamientoDAO.registrarSalida(
                idInternamientoSeleccionado,
                jComboBoxMotivoSalida.getSelectedItem().toString(),
                jTextAreaObsSalida.getText().trim()
        );
        jLabel13.setText("Salida registrada a las "
                + java.time.LocalTime.now().withNano(0) + ".");
        jTextAreaObsSalida.setText("");
        idInternamientoSeleccionado = -1;
        cargarTablaInternamientos();
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al registrar salida: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonRegistrarSalidaActionPerformed

    private void jButtonLimpiarInternamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarInternamientoActionPerformed
        // TODO add your handling code here:
        jTextFieldMotivoEntrada.setText("");
    jTextAreaObsEntrada.setText("");
    jTextAreaObsSalida.setText("");
    idInternamientoSeleccionado = -1;
    jTableInternamientos.clearSelection();
    }//GEN-LAST:event_jButtonLimpiarInternamientoActionPerformed

    private void jButtonActualizarInternamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarInternamientoActionPerformed
        // TODO add your handling code here:
        if (idInternamientoSeleccionado == -1) {
        jLabel13.setText("Selecciona en la tabla el internamiento a corregir.");
        return;
    }
    if (jTextFieldMotivoEntrada.getText().trim().isEmpty()) {
        jLabel13.setText("Escribe el motivo de entrada.");
        return;
    }

    try {
        InternamientoDAO.actualizarDatosEntrada(
                idInternamientoSeleccionado,
                jTextFieldMotivoEntrada.getText().trim(),
                jTextAreaObsEntrada.getText().trim()
        );
        jLabel13.setText("Datos de entrada actualizados.");
        cargarTablaInternamientos();
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al actualizar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonActualizarInternamientoActionPerformed

    private void jButtonRegresaralMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresaralMenuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonRegresaralMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInternamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInternamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInternamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInternamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInternamiento().setVisible(true);
            }
        });
    }

    
    
    
    
    
    // ===== Cargar combo de pacientes (solo para el registro de entrada) =====
private void cargarComboPacientes() {
    try {
        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        for (Object[] fila : PacienteDAO.listarTodos()) {
            String id = fila[0].toString();
            String nombre = fila[1] + " " + fila[2]; // nombre + apellido paterno
            modelo.addElement(new ComboItem(id, id + " — " + nombre));
        }
        jComboBoxPacienteInt.setModel(modelo);
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al cargar pacientes: " + e.getMessage());
    }
}

// ===== Cargar combo de médicos =====
private void cargarComboMedicos() {
    try {
        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        for (Object[] fila : MedicoDAO.listarTodos()) {
            String id = fila[0].toString();
            String nombre = fila[1] + " " + fila[2]; // nombre + apellido paterno
            modelo.addElement(new ComboItem(id, nombre));
        }
        jComboBoxMedicoResponsable.setModel(modelo);
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al cargar médicos: " + e.getMessage());
    }
}

// ===== Cargar la tabla de internamientos =====
private void cargarTablaInternamientos() {
    try {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) jTableInternamientos.getModel();
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new String[]{
            "ID", "Paciente", "F. Entrada", "H. Entrada", "F. Salida", "H. Salida", "Estado"
        });

        for (Object[] fila : InternamientoDAO.listarTodos()) {
            modelo.addRow(fila);
        }
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al cargar internamientos: " + e.getMessage());
    }
}






    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarInternamiento;
    private javax.swing.JButton jButtonLimpiarInternamiento;
    private javax.swing.JButton jButtonRegistrarEntrada;
    private javax.swing.JButton jButtonRegistrarSalida;
    private javax.swing.JButton jButtonRegresaralMenu;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBoxMedicoResponsable;
    private javax.swing.JComboBox<String> jComboBoxMotivoSalida;
    private javax.swing.JComboBox<String> jComboBoxPacienteInt;
    private javax.swing.JPanel jComboBoxTipoPaciente;
    private com.toedter.calendar.JDateChooser jDateChooserEntrada;
    private com.toedter.calendar.JDateChooser jDateChooserSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInternamientos;
    private javax.swing.JTextField jTextAreaObsEntrada;
    private javax.swing.JTextField jTextAreaObsSalida;
    private javax.swing.JTextField jTextFieldMotivoEntrada;
    // End of variables declaration//GEN-END:variables
}
