/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danim
 */
public class FrameMedicos extends javax.swing.JFrame {

    /**
     * Creates new form FrameMedicos
     */
    public FrameMedicos() {
        initComponents();
        cargarTablaMedicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreMedico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApMaterno = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldHospital = new javax.swing.JTextField();
        jFormattedTextFieldTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBoxEspecialidad = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonActualizarMedico = new javax.swing.JButton();
        jButtonEliminarMedico = new javax.swing.JButton();
        jButtonLimpiarMedico = new javax.swing.JButton();
        jButtonMenuP = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alta / Edición Médicos");

        jLabel2.setText("Nombre(s)");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Cédula Profesional");

        jLabel6.setText("Especialidad");

        jLabel7.setText("Hospital");

        jLabel8.setText("Teléfono");

        jLabel9.setText("Correo electrónico");

        jComboBoxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pediatria", "Internista", "Cardiología", "Cirugia", "Odontología", "Epidemiología", "Urgencias" }));

        jLabel10.setText("Médicos Registrados");

        jTableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMedicos);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonActualizarMedico.setText("Actualizar");
        jButtonActualizarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarMedicoActionPerformed(evt);
            }
        });

        jButtonEliminarMedico.setBackground(new java.awt.Color(255, 102, 102));
        jButtonEliminarMedico.setText("Eliminar");
        jButtonEliminarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarMedicoActionPerformed(evt);
            }
        });

        jButtonLimpiarMedico.setText("Limpiar");
        jButtonLimpiarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarMedicoActionPerformed(evt);
            }
        });

        jButtonMenuP.setText("Regresar");
        jButtonMenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuPActionPerformed(evt);
            }
        });

        jLabel11.setText("info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldApMaterno)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNombreMedico)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldTelefono)
                                .addComponent(jComboBoxEspecialidad, 0, 388, Short.MAX_VALUE))
                            .addGap(76, 76, 76)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldHospital)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldApPaterno)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCedula)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMenuP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonActualizarMedico)
                    .addComponent(jButtonEliminarMedico)
                    .addComponent(jButtonLimpiarMedico)
                    .addComponent(jButtonMenuP))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldNombreMedico.getText().trim().isEmpty()
            || jTextFieldApPaterno.getText().trim().isEmpty()
            || jTextFieldCedula.getText().trim().isEmpty()) {
        jLabel11.setText("Nombre, apellido paterno y cédula son obligatorios.");
        return;
    }

    try {
        MedicoDAO.guardar(
                jTextFieldNombreMedico.getText().trim(),
                jTextFieldApPaterno.getText().trim(),
                jTextFieldApMaterno.getText().trim(),
                jTextFieldCedula.getText().trim(),
                jComboBoxEspecialidad.getSelectedItem().toString(),
                jTextFieldHospital.getText().trim(),
                jFormattedTextFieldTelefono.getText().trim(),
                jTextField7.getText().trim()
        );
        jLabel11.setText("Médico guardado correctamente.");
        limpiarCamposMedico();
        cargarTablaMedicos();
    } catch (java.sql.SQLException e) {
        jLabel11.setText("Error al guardar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonActualizarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarMedicoActionPerformed
        // TODO add your handling code here:
        int fila = jTableMedicos.getSelectedRow();
    if (fila == -1) {
        jLabel11.setText("Selecciona un médico de la tabla para actualizar.");
        return;
    }
    int idMedico = (int) jTableMedicos.getValueAt(fila, 0);

    try {
        MedicoDAO.actualizar(idMedico,
                jTextFieldNombreMedico.getText().trim(),
                jTextFieldApPaterno.getText().trim(),
                jTextFieldApMaterno.getText().trim(),
                jTextFieldCedula.getText().trim(),
                jComboBoxEspecialidad.getSelectedItem().toString(),
                jTextFieldHospital.getText().trim(),
                jFormattedTextFieldTelefono.getText().trim(),
                jTextField7.getText().trim()
        );
        jLabel11.setText("Médico actualizado.");
        limpiarCamposMedico();
        cargarTablaMedicos();
    } catch (java.sql.SQLException e) {
        jLabel11.setText("Error al actualizar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonActualizarMedicoActionPerformed

    private void jButtonEliminarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarMedicoActionPerformed
        // TODO add your handling code here:
        int fila = jTableMedicos.getSelectedRow();
    if (fila == -1) {
        jLabel11.setText("Selecciona un médico de la tabla para eliminar.");
        return;
    }
    int idMedico = (int) jTableMedicos.getValueAt(fila, 0);

    try {
        MedicoDAO.eliminar(idMedico);
        jLabel11.setText("Médico eliminado.");
        limpiarCamposMedico();
        cargarTablaMedicos();
    } catch (java.sql.SQLException e) {
        jLabel11.setText("Error al eliminar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonEliminarMedicoActionPerformed

    private void jButtonLimpiarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarMedicoActionPerformed
        // TODO add your handling code here:
        limpiarCamposMedico();
    }//GEN-LAST:event_jButtonLimpiarMedicoActionPerformed

    private void jButtonMenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuPActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonMenuPActionPerformed

    private void jTableMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMedicosMouseClicked
        // TODO add your handling code here:
            int fila = jTableMedicos.getSelectedRow();
    if (fila == -1) return;

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTableMedicos.getModel();

    jTextFieldNombreMedico.setText(modelo.getValueAt(fila, 1).toString());
    jTextFieldApPaterno.setText(modelo.getValueAt(fila, 2).toString());
    jTextFieldApMaterno.setText(modelo.getValueAt(fila, 3) == null ? "" : modelo.getValueAt(fila, 3).toString());
    jTextFieldCedula.setText(modelo.getValueAt(fila, 4).toString());
    jComboBoxEspecialidad.setSelectedItem(modelo.getValueAt(fila, 5) == null ? "" : modelo.getValueAt(fila, 5).toString());
    jTextFieldHospital.setText(modelo.getValueAt(fila, 6) == null ? "" : modelo.getValueAt(fila, 6).toString());
    jFormattedTextFieldTelefono.setText(modelo.getValueAt(fila, 7) == null ? "" : modelo.getValueAt(fila, 7).toString());
    jTextField7.setText(modelo.getValueAt(fila, 8) == null ? "" : modelo.getValueAt(fila, 8).toString());
    }//GEN-LAST:event_jTableMedicosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMedicos().setVisible(true);
            }
        });
    }
    
    
    
    // ===== Cargar la tabla de médicos =====
private void cargarTablaMedicos() {
    try {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) jTableMedicos.getModel();
        modelo.setRowCount(0); // limpia filas previas
        modelo.setColumnIdentifiers(new String[]{
            "ID", "Nombre", "Ap. Paterno", "Ap. Materno",
            "Cédula", "Especialidad", "Hospital", "Teléfono", "Correo"
        });

        for (Object[] fila : MedicoDAO.listarTodos()) {
            modelo.addRow(fila);
        }
    } catch (java.sql.SQLException e) {
        jLabel11.setText("Error al cargar médicos: " + e.getMessage());
    }
}

// ===== Limpiar campos =====
private void limpiarCamposMedico() {
    jTextFieldNombreMedico.setText("");
    jTextFieldApPaterno.setText("");
    jTextFieldApMaterno.setText("");
    jTextFieldCedula.setText("");
    jTextFieldHospital.setText("");
    jFormattedTextFieldTelefono.setText("");
    jTextField7.setText(""); // correo
    jComboBoxEspecialidad.setSelectedIndex(0);
    jTableMedicos.clearSelection();
}








    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonActualizarMedico;
    private javax.swing.JButton jButtonEliminarMedico;
    private javax.swing.JButton jButtonLimpiarMedico;
    private javax.swing.JButton jButtonMenuP;
    private javax.swing.JComboBox<String> jComboBoxEspecialidad;
    private javax.swing.JTextField jFormattedTextFieldTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicos;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldApMaterno;
    private javax.swing.JTextField jTextFieldApPaterno;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldHospital;
    private javax.swing.JTextField jTextFieldNombreMedico;
    // End of variables declaration//GEN-END:variables
}
