/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danim
 */

import java.util.List;


public class FrameConsulta extends javax.swing.JFrame {

    /**
     * Creates new form FrameConsulta
     */
    public FrameConsulta() {
        initComponents();
    jDateChooserFechaConsulta.setEnabled(false);
    cargarComboPacientes();
    cargarComboMedicos();
    cargarTablaConsultas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPacienteConsulta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxMedicoConsulta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxInternamientoConsulta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextAreaDiagnostico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextAreaObsConsulta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooserFechaConsulta = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultas = new javax.swing.JTable();
        jButtonGuardarConsulta = new javax.swing.JButton();
        jButtonActualizarConsulta = new javax.swing.JButton();
        jButtonEliminarConsulta = new javax.swing.JButton();
        jButtonIrAReceta = new javax.swing.JButton();
        jButtonRegresarAlMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Consulta");

        jLabel2.setText("Paciente");

        jComboBoxPacienteConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPacienteConsulta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPacienteConsultaItemStateChanged(evt);
            }
        });
        jComboBoxPacienteConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPacienteConsultaActionPerformed(evt);
            }
        });

        jLabel3.setText("Médico");

        jComboBoxMedicoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Internamiento Asociado");

        jComboBoxInternamientoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Diagnóstico");

        jLabel6.setText("Observaciones");

        jLabel7.setText("Fecha ");

        jLabel8.setText("Consultas Registradas");

        jTableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultas);

        jButtonGuardarConsulta.setBackground(new java.awt.Color(153, 204, 255));
        jButtonGuardarConsulta.setText("Guardar");
        jButtonGuardarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarConsultaActionPerformed(evt);
            }
        });

        jButtonActualizarConsulta.setText("Actualizar");
        jButtonActualizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarConsultaActionPerformed(evt);
            }
        });

        jButtonEliminarConsulta.setBackground(new java.awt.Color(255, 102, 102));
        jButtonEliminarConsulta.setText("Eliminar");
        jButtonEliminarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarConsultaActionPerformed(evt);
            }
        });

        jButtonIrAReceta.setText("Ir a Recetas");
        jButtonIrAReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrARecetaActionPerformed(evt);
            }
        });

        jButtonRegresarAlMenu.setText("Regresar");
        jButtonRegresarAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarAlMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextAreaObsConsulta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(jComboBoxInternamientoConsulta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(62, 62, 62))
                                    .addComponent(jTextAreaDiagnostico)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPacienteConsulta, 0, 349, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMedicoConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserFechaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonRegresarAlMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonGuardarConsulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonActualizarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonIrAReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 78, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxMedicoConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPacienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxInternamientoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAreaDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAreaObsConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserFechaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarConsulta)
                    .addComponent(jButtonActualizarConsulta)
                    .addComponent(jButtonEliminarConsulta)
                    .addComponent(jButtonIrAReceta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegresarAlMenu)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarConsultaActionPerformed
        // TODO add your handling code here:
        ComboItem paciente = (ComboItem) jComboBoxPacienteConsulta.getSelectedItem();
    ComboItem medico = (ComboItem) jComboBoxMedicoConsulta.getSelectedItem();
    ComboItem internamiento = (ComboItem) jComboBoxInternamientoConsulta.getSelectedItem();

    if (paciente == null || medico == null || jTextAreaDiagnostico.getText().trim().isEmpty()) {
        jLabel8.setText("Selecciona paciente, médico y escribe el diagnóstico.");
        return;
    }

    try {
        Integer idInternamiento = (internamiento == null || internamiento.getId() == null)
                ? null : Integer.parseInt(internamiento.getId());

        ConsultaDAO.guardar(
                paciente.getId(),
                Integer.parseInt(medico.getId()),
                idInternamiento,
                jTextAreaDiagnostico.getText().trim(),
                jTextAreaObsConsulta.getText().trim()
        );
        jLabel8.setText("Consulta guardada correctamente.");
        limpiarCamposConsulta();
        cargarTablaConsultas();
    } catch (java.sql.SQLException e) {
        jLabel8.setText("Error al guardar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonGuardarConsultaActionPerformed

    private void jButtonActualizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarConsultaActionPerformed
        // TODO add your handling code here:
        if (idConsultaSeleccionada == -1) {
        jLabel8.setText("Selecciona una consulta de la tabla para actualizar.");
        return;
    }

    try {
        ConsultaDAO.actualizar(idConsultaSeleccionada,
                jTextAreaDiagnostico.getText().trim(),
                jTextAreaObsConsulta.getText().trim());
        jLabel8.setText("Consulta actualizada.");
        limpiarCamposConsulta();
        cargarTablaConsultas();
    } catch (java.sql.SQLException e) {
        jLabel8.setText("Error al actualizar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonActualizarConsultaActionPerformed

    private void jButtonEliminarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarConsultaActionPerformed
        // TODO add your handling code here:
        if (idConsultaSeleccionada == -1) {
        jLabel8.setText("Selecciona una consulta de la tabla para eliminar.");
        return;
    }

    try {
        ConsultaDAO.eliminar(idConsultaSeleccionada);
        jLabel8.setText("Consulta eliminada.");
        limpiarCamposConsulta();
        cargarTablaConsultas();
    } catch (java.sql.SQLException e) {
        jLabel8.setText("Error al eliminar (revisa que no tenga una receta asociada): " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonEliminarConsultaActionPerformed

    private void jButtonIrARecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrARecetaActionPerformed
        // TODO add your handling code here:
        if (idConsultaSeleccionada == -1) {
        jLabel8.setText("Selecciona una consulta de la tabla para emitirle receta.");
        return;
    }
    FrameRecetas frame = new FrameRecetas(idConsultaSeleccionada);
    frame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonIrARecetaActionPerformed

    private int idConsultaSeleccionada = -1;
    private void jTableConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultasMouseClicked
        // TODO add your handling code here:
        int fila = jTableConsultas.getSelectedRow();
    if (fila == -1) return;

    idConsultaSeleccionada = (int) jTableConsultas.getValueAt(fila, 0);
    jTextAreaDiagnostico.setText(jTableConsultas.getValueAt(fila, 4) == null
            ? "" : jTableConsultas.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_jTableConsultasMouseClicked

    private void jComboBoxPacienteConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPacienteConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPacienteConsultaActionPerformed

    private void jButtonRegresarAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarAlMenuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonRegresarAlMenuActionPerformed

    private void jComboBoxPacienteConsultaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPacienteConsultaItemStateChanged
        // TODO add your handling code here:
        cargarComboInternamientos();
                
    }//GEN-LAST:event_jComboBoxPacienteConsultaItemStateChanged

    
    
    
    



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameConsulta().setVisible(true);
            }
        });
    }

    
    
    
    
    private void cargarComboPacientes() {
    try {
        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        for (Object[] fila : PacienteDAO.listarTodos()) {
            String id = fila[0].toString();
            String nombre = fila[1] + " " + fila[2];
            modelo.addElement(new ComboItem(id, id + " — " + nombre));
        }
        jComboBoxPacienteConsulta.setModel(modelo);
        cargarComboInternamientos(); // refresca internamientos del primer paciente
    } catch (java.sql.SQLException e) {
        jLabel8.setText("Error al cargar pacientes: " + e.getMessage());
    }
}

// ===== Cargar combo de médicos =====
private void cargarComboMedicos() {
    try {
        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        for (Object[] fila : MedicoDAO.listarTodos()) {
            String id = fila[0].toString();
            String nombre = fila[1] + " " + fila[2];
            modelo.addElement(new ComboItem(id, nombre));
        }
        jComboBoxMedicoConsulta.setModel(modelo);
    } catch (java.sql.SQLException e) {
        jLabel8.setText("Error al cargar médicos: " + e.getMessage());
    }
}

// ===== Cargar combo de internamientos ACTIVOS del paciente seleccionado =====
private void cargarComboInternamientos() {
    ComboItem paciente = (ComboItem) jComboBoxPacienteConsulta.getSelectedItem();
    javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
    modelo.addElement(new ComboItem(null, "— Ninguno (consulta externa) —"));

    if (paciente != null) {
        try {
            for (Object[] fila : ConsultaDAO.listarInternamientosActivos(paciente.getId())) {
                String id = fila[0].toString();
                modelo.addElement(new ComboItem(id, "Internamiento #" + id + " (" + fila[1] + ")"));
            }
        } catch (java.sql.SQLException e) {
            jLabel8.setText("Error al cargar internamientos: " + e.getMessage());
        }
    }
    jComboBoxInternamientoConsulta.setModel(modelo);
}

// ===== Cargar la tabla de consultas =====
private void cargarTablaConsultas() {
    try {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) jTableConsultas.getModel();
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new String[]{
            "ID", "Paciente", "Médico", "Fecha", "Diagnóstico"
        });

        for (Object[] fila : ConsultaDAO.listarTodos()) {
            modelo.addRow(fila);
        }
    } catch (java.sql.SQLException e) {
        jLabel8.setText("Error al cargar consultas: " + e.getMessage());
    }
}

// ===== Limpiar campos =====
private void limpiarCamposConsulta() {
    jTextAreaDiagnostico.setText("");
    jTextAreaObsConsulta.setText("");
    idConsultaSeleccionada = -1;
    jTableConsultas.clearSelection();
}
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarConsulta;
    private javax.swing.JButton jButtonEliminarConsulta;
    private javax.swing.JButton jButtonGuardarConsulta;
    private javax.swing.JButton jButtonIrAReceta;
    private javax.swing.JButton jButtonRegresarAlMenu;
    private javax.swing.JComboBox<String> jComboBoxInternamientoConsulta;
    private javax.swing.JComboBox<String> jComboBoxMedicoConsulta;
    private javax.swing.JComboBox<String> jComboBoxPacienteConsulta;
    private com.toedter.calendar.JDateChooser jDateChooserFechaConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultas;
    private javax.swing.JTextField jTextAreaDiagnostico;
    private javax.swing.JTextField jTextAreaObsConsulta;
    // End of variables declaration//GEN-END:variables
}
