/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danim
 */

import java.util.List;
public class FramePacientes extends javax.swing.JFrame {

    /**
     * Creates new form FramePacientes
     */
    public FramePacientes() {
        initComponents();
        cargarTablaPacientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApPaternoPac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldApMaternoPac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldTelPac = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCorreoPac = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jDateChooserNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldIdPaciente = new javax.swing.JTextField();
        jComboBoxTipoSangre = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jButtonGuardarPaciente = new javax.swing.JButton();
        jButtonActualizarPaciente = new javax.swing.JButton();
        jButtonBuscarPaciente = new javax.swing.JButton();
        jButtonEliminarPaciente = new javax.swing.JButton();
        jButtonLimpiarPaciente = new javax.swing.JButton();
        jButtonRegresoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alta Pacientes");

        jLabel2.setText("Nombre(s)");

        jTextFieldNombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombrePacienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Peso (kg)");

        jLabel6.setText("Género");

        jLabel7.setText("Fecha de nacimiento");

        jLabel8.setText("Teléfono");

        jLabel9.setText("Correo Electrónico");

        jLabel10.setText("Altura");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel11.setText("Tipo de sangre");

        jLabel12.setText("Identificador");

        jComboBoxTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));

        jLabel13.setText("Pacientes Registrados");

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        jButtonGuardarPaciente.setBackground(new java.awt.Color(153, 204, 255));
        jButtonGuardarPaciente.setText("Guardar");
        jButtonGuardarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPacienteActionPerformed(evt);
            }
        });

        jButtonActualizarPaciente.setText("Actualizar");
        jButtonActualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarPacienteActionPerformed(evt);
            }
        });

        jButtonBuscarPaciente.setText("Buscar");
        jButtonBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPacienteActionPerformed(evt);
            }
        });

        jButtonEliminarPaciente.setBackground(new java.awt.Color(255, 102, 102));
        jButtonEliminarPaciente.setText("Eliminar");
        jButtonEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPacienteActionPerformed(evt);
            }
        });

        jButtonLimpiarPaciente.setText("Limpiar");
        jButtonLimpiarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarPacienteActionPerformed(evt);
            }
        });

        jButtonRegresoMenu.setText("Regresar");
        jButtonRegresoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldTelPac, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldApMaternoPac, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNombrePaciente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxGenero, 0, 173, Short.MAX_VALUE))
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooserNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(70, 70, 70)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldApPaternoPac)
                                .addComponent(jTextFieldCorreoPac)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPeso)
                                        .addComponent(jComboBoxTipoSangre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldAltura)
                                        .addComponent(jTextFieldIdPaciente)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonGuardarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegresoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApPaternoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApMaternoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTelPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCorreoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDateChooserNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarPaciente)
                    .addComponent(jButtonActualizarPaciente)
                    .addComponent(jButtonBuscarPaciente)
                    .addComponent(jButtonEliminarPaciente)
                    .addComponent(jButtonLimpiarPaciente)
                    .addComponent(jButtonRegresoMenu))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombrePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePacienteActionPerformed

    private void jButtonGuardarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPacienteActionPerformed
 String id = jTextFieldIdPaciente.getText().trim();

    if (id.isEmpty() || jTextFieldNombrePaciente.getText().trim().isEmpty()
            || jTextFieldApPaternoPac.getText().trim().isEmpty()
            || jDateChooserNacimiento.getDate() == null) {
        jLabel13.setText("Expediente, nombre, apellido paterno y fecha de nacimiento son obligatorios.");
        return;
    }

    try {
        if (PacienteDAO.existe(id)) {
            jLabel13.setText("Ya existe un paciente con el expediente " + id + ".");
            return;
        }

        double peso = jTextFieldPeso.getText().trim().isEmpty() ? 0
                : Double.parseDouble(jTextFieldPeso.getText().trim());
        double altura = jTextFieldAltura.getText().trim().isEmpty() ? 0
                : Double.parseDouble(jTextFieldAltura.getText().trim());
        java.sql.Date fechaNac = new java.sql.Date(jDateChooserNacimiento.getDate().getTime());

        PacienteDAO.guardar(id,
                jTextFieldNombrePaciente.getText().trim(),
                jTextFieldApPaternoPac.getText().trim(),
                jTextFieldApMaternoPac.getText().trim(),
                jComboBoxGenero.getSelectedItem().toString(),
                fechaNac, peso, altura,
                jComboBoxTipoSangre.getSelectedItem().toString(),
                jFormattedTextFieldTelPac.getText().trim(),
                jTextFieldCorreoPac.getText().trim()
        );
        jLabel13.setText("Paciente guardado correctamente.");
        limpiarCamposPaciente();
        cargarTablaPacientes();
    } catch (NumberFormatException e) {
        jLabel13.setText("Peso y altura deben ser números (ej. 68.50).");
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al guardar: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarPacienteActionPerformed

    private void jButtonLimpiarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarPacienteActionPerformed
        // TODO add your handling code here:
            limpiarCamposPaciente();

    }//GEN-LAST:event_jButtonLimpiarPacienteActionPerformed

    private void jButtonActualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarPacienteActionPerformed

        // TODO add your handling code here:
        String id = jTextFieldIdPaciente.getText().trim();
    if (id.isEmpty()) {
        jLabel13.setText("Selecciona un paciente de la tabla para actualizar.");
        return;
    }

    try {
        double peso = jTextFieldPeso.getText().trim().isEmpty() ? 0
                : Double.parseDouble(jTextFieldPeso.getText().trim());
        double altura = jTextFieldAltura.getText().trim().isEmpty() ? 0
                : Double.parseDouble(jTextFieldAltura.getText().trim());
        java.sql.Date fechaNac = new java.sql.Date(jDateChooserNacimiento.getDate().getTime());

        PacienteDAO.actualizar(id,
                jTextFieldNombrePaciente.getText().trim(),
                jTextFieldApPaternoPac.getText().trim(),
                jTextFieldApMaternoPac.getText().trim(),
                jComboBoxGenero.getSelectedItem().toString(),
                fechaNac, peso, altura,
                jComboBoxTipoSangre.getSelectedItem().toString(),
                jFormattedTextFieldTelPac.getText().trim(),
                jTextFieldCorreoPac.getText().trim()
        );
        jLabel13.setText("Paciente actualizado.");
        limpiarCamposPaciente();
        cargarTablaPacientes();
    } catch (NumberFormatException e) {
        jLabel13.setText("Peso y altura deben ser números.");
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al actualizar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonActualizarPacienteActionPerformed

    private void jTablePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseClicked
        // TODO add your handling code here:
        int fila = jTablePacientes.getSelectedRow();
    if (fila == -1) return;

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTablePacientes.getModel();

    jTextFieldIdPaciente.setText(modelo.getValueAt(fila, 0).toString());
    jTextFieldIdPaciente.setEnabled(false); // el expediente no se edita una vez creado
    jTextFieldNombrePaciente.setText(modelo.getValueAt(fila, 1).toString());
    jTextFieldApPaternoPac.setText(modelo.getValueAt(fila, 2).toString());
    jTextFieldApMaternoPac.setText(modelo.getValueAt(fila, 3) == null ? "" : modelo.getValueAt(fila, 3).toString());
    jComboBoxGenero.setSelectedItem(modelo.getValueAt(fila, 4) == null ? "" : modelo.getValueAt(fila, 4).toString());

    Object fechaObj = modelo.getValueAt(fila, 5);
    if (fechaObj != null) {
        jDateChooserNacimiento.setDate((java.util.Date) fechaObj);
    }

    jTextFieldPeso.setText(modelo.getValueAt(fila, 6).toString());
    jTextFieldAltura.setText(modelo.getValueAt(fila, 7).toString());
    jComboBoxTipoSangre.setSelectedItem(modelo.getValueAt(fila, 8) == null ? "" : modelo.getValueAt(fila, 8).toString());
    jFormattedTextFieldTelPac.setText(modelo.getValueAt(fila, 9) == null ? "" : modelo.getValueAt(fila, 9).toString());
    jTextFieldCorreoPac.setText(modelo.getValueAt(fila, 10) == null ? "" : modelo.getValueAt(fila, 10).toString());
    }//GEN-LAST:event_jTablePacientesMouseClicked

    private void jButtonEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPacienteActionPerformed
        // TODO add your handling code here:
          String id = jTextFieldIdPaciente.getText().trim();
    if (id.isEmpty()) {
        jLabel13.setText("Selecciona un paciente de la tabla para eliminar.");
        return;
    }

    try {
        PacienteDAO.eliminar(id);
        jLabel13.setText("Paciente eliminado.");
        limpiarCamposPaciente();
        cargarTablaPacientes();
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al eliminar (revisa que no tenga consultas o internamientos ligados): " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonEliminarPacienteActionPerformed

    private void jButtonBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPacienteActionPerformed
        // TODO add your handling code here:
        String texto = jTextFieldIdPaciente.getText().trim();
    if (texto.isEmpty()) {
        texto = jTextFieldNombrePaciente.getText().trim();
    }
    if (texto.isEmpty()) {
        jLabel13.setText("Escribe un expediente o nombre para buscar.");
        return;
    }

    try {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) jTablePacientes.getModel();
        modelo.setRowCount(0);

        List<Object[]> resultados = PacienteDAO.buscar(texto);
        for (Object[] fila : resultados) {
            modelo.addRow(fila);
        }
        jLabel13.setText(resultados.size() + " resultado(s) encontrado(s).");
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al buscar: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonBuscarPacienteActionPerformed

    private void jButtonRegresoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresoMenuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonRegresoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePacientes().setVisible(true);
            }
        });
    }
    
    
    
    
    // ===== Cargar la tabla de pacientes =====
private void cargarTablaPacientes() {
    try {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) jTablePacientes.getModel();
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new String[]{
            "Expediente", "Nombre", "Ap. Paterno", "Ap. Materno", "Género",
            "F. Nacimiento", "Peso", "Altura", "Tipo Sangre", "Teléfono", "Correo"
        });

        for (Object[] fila : PacienteDAO.listarTodos()) {
            modelo.addRow(fila);
        }
    } catch (java.sql.SQLException e) {
        jLabel13.setText("Error al cargar pacientes: " + e.getMessage());
    }
}

// ===== Limpiar campos =====
private void limpiarCamposPaciente() {
    jTextFieldIdPaciente.setText("");
    jTextFieldIdPaciente.setEnabled(true); // por si estaba bloqueado tras seleccionar uno
    jTextFieldNombrePaciente.setText("");
    jTextFieldApPaternoPac.setText("");
    jTextFieldApMaternoPac.setText("");
    jTextFieldPeso.setText("");
    jTextFieldAltura.setText("");
    jFormattedTextFieldTelPac.setText("");
    jTextFieldCorreoPac.setText("");
    jComboBoxGenero.setSelectedIndex(0);
    jComboBoxTipoSangre.setSelectedIndex(0);
    jDateChooserNacimiento.setDate(null);
    jTablePacientes.clearSelection();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarPaciente;
    private javax.swing.JButton jButtonBuscarPaciente;
    private javax.swing.JButton jButtonEliminarPaciente;
    private javax.swing.JButton jButtonGuardarPaciente;
    private javax.swing.JButton jButtonLimpiarPaciente;
    private javax.swing.JButton jButtonRegresoMenu;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JComboBox<String> jComboBoxTipoSangre;
    private com.toedter.calendar.JDateChooser jDateChooserNacimiento;
    private javax.swing.JTextField jFormattedTextFieldTelPac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldApMaternoPac;
    private javax.swing.JTextField jTextFieldApPaternoPac;
    private javax.swing.JTextField jTextFieldCorreoPac;
    private javax.swing.JTextField jTextFieldIdPaciente;
    private javax.swing.JTextField jTextFieldNombrePaciente;
    private javax.swing.JTextField jTextFieldPeso;
    // End of variables declaration//GEN-END:variables
}
